### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by jellehak** [Flamenco/admin-power-tools#1] opened 2019-03-19 09:44 UTC
This plugin doesn't take notice of the admin environment being set by : "administrator path" field from the admin plugin.

**Comment by Flamenco** [comment] 2019-03-19 10:57
Can you please let me know what you set the path to, and descibe in detail the error you encountered?

**Comment by revta** [comment] 2019-08-20 03:29
I have the same issue. You can set a custom path to the admin dashboard by copying the user/plugins/admin/admin.yaml file to user/config/plugins/admin.yaml. This sets the "administrator path" field to whatever your new admin path is. (You can also set this by going to the admin panel under plugins and changing the administrator path) (( Or check "Custom Admin Url @ this https://learn.getgrav.org/16/admin-panel/faq))

For example, Let's say mine is set to  "/superSecretAdmin".  

When I click on "Reports", added by this plugin, it opens to: 
ht<span>tp://</span>www.sitename.com/admin/admin-power-tools/reports, 
when it should open to:
 ht<span>tp://www.sitename.com/superSecretAdmin/admin-power-tools/reports. 
When you go to the second url the plugin works and the reports are good after that.

**Comment by Flamenco** [comment] 2019-08-20 13:14
@revta Thanks for the details.  We will have a look ASAP.

**Comment by Flamenco** [comment] 2019-08-22 12:37
Fixed in 0.1.11

**Closed as completed by Flamenco** 2019-08-22 12:37 UTC
Labels: bug

**Comment by 001101** [comment] 2019-09-05 17:59
https://github.com/getgrav/grav-plugin-admin/blob/c1f733e402aac619d2ab22f20b32dfb21f19f100/admin.php#L135

**Comment by 001101** [comment] 2019-09-05 18:03
Have to reopen the issue, the url is not interpreted correctly if grav is installed in a subdirectory.

**Comment by Flamenco** [comment] 2019-09-05 21:56
@001101 Can you post the expected url path, actual url path, and location of the grav folder relative to the root directory?

**Comment by 001101** [comment] 2019-09-07 14:01
expect to read the root directory and do the correct routing including a possible subdirectory

**Comment by Flamenco** [comment] 2019-09-07 16:25
@001101 We are going to need a specific reproducible case to track this down.  For example:

```
expected url path: https//foo.com/myadmin
actual url path: https//foo.com/admin 
location of the grav folder relative to the root directory: /home/me/www/grav
```
Also, is your admin page the default? `/my.site/admin`.

**Comment by 001101** [comment] 2019-09-10 14:33
https://stackoverflow.com/questions/32537477/how-to-use-dir

**Comment by Flamenco** [comment] 2019-09-10 15:58
@001101 We know how to use PHP over here.  If you do not convey details about your specific use-case and configuration, it is very for us to reproduce.   We have grav installations installed in many different subdirectories and have no issues.

1. Is your admin page the default URL path?
2. What is the error you are receiving?
3. What is the URL when you receive the error?

**Comment by RCheesley** [comment] 2020-03-06 13:14
Hi @Flamenco I have this problem also since enabling a non-standard admin panel all my edit links are broken front-end. It worked fine if I use the standard /admin/ route.

Grav v1.6.22 - Admin v1.9.13 - Admin Power Tools v0.1.12

All the edit buttons from Admin Power Tools seem to be hard-coded to use /admin - example:

https://mysite/admin/powertools/edit-section/?section=%23%23+Introduction

Whereas my URL is not /admin/ - it is using a custom URL for security reasons.

When I land on those pages I get a 404 not found.

**Comment by HunterDG** [comment] 2020-05-22 00:05
anyone have this plugin working on Grav 1.6.25/admin 1.

it breaks my instance with "Trying to access array offset on value of type null" at `return $config->grav['base_url_relative'] . $base;`

(using standard /admin path)

**Comment by Allamaris0** [comment] 2020-06-09 18:39
I got the same error during installation of admin power tools. I must have removed it manually because it crashed admin panel.
